<a href='https://www2.howard.edu'> <img src='../hu_logo.png'/></a>

In [4]:
import numpy as np
import pandas as pd

In [13]:
array_1 = np.array([1,2,3,4])

In [14]:
array_2 = np.array([4,3,2,1])

In [16]:
len(array_1)+1

5

In [23]:
for i in range(len(array_1)):
    dot = array_1[i]*array_2.sum()
    dot
    #Do not use this

In [24]:
dot

40

In [25]:
array_1@array_2

20

In [26]:
array_1.dot(array_2)

20

In [27]:
array_3 = np.sqrt(array_1)

In [28]:
array_3

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [31]:
another_arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
another_arr[0:5]

array([1, 2, 3, 4, 5])

# Broadcasting

In [33]:
another_arr[0:5]=100

In [34]:
another_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [35]:
another_arr[:] = 1

In [36]:
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
three_by_three = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [47]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#three_by_three[:]  = 0

In [49]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
# I want to grab the first column in three_by_three

In [52]:
three_by_three[0]

array([1, 2, 3])

In [53]:
#Slicing _ HW due this Monday.

array([1])

In [55]:
three_by_three > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [56]:
new_matrix = three_by_three > 4

In [57]:
new_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [58]:
# Split method

In [59]:
# Given a string s ='a b c d', I want to find a list in the form ['a','b', 'c','d']

In [61]:
s ='a b c d'
a_list = []
for char in s:
    if char == ' ':
        continue
    else:
        a_list.append(char)
    a_list

In [62]:
a_list

['a', 'b', 'c', 'd']

In [63]:
s.split()

['a', 'b', 'c', 'd']

In [66]:
s = 'ab,c,d'

In [67]:
s.split(',')

['ab', 'c', 'd']

In [68]:
from numpy.random import randn

In [70]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [71]:
df

W         X         Y         Z
A  0.099022 -0.747121  1.066118  2.835370
B  2.742849  2.984470 -0.170398  1.384525
C  1.037328 -0.318614 -0.101749 -0.091330
D  2.341230  0.528923 -0.507544  1.312976
E  1.283571 -0.322914 -0.247309 -1.025842

In [72]:
df['W']

A    0.099022
B    2.742849
C    1.037328
D    2.341230
E    1.283571
Name: W, dtype: float64

In [74]:
# I want to grab the first two columns
df[['W', 'X']]

W         X
A  0.099022 -0.747121
B  2.742849  2.984470
C  1.037328 -0.318614
D  2.341230  0.528923
E  1.283571 -0.322914

In [76]:
type(df.W)

pandas.core.series.Series

In [77]:
df['New'] = df['W']+df['Y']

In [78]:
df

W         X         Y         Z       New
A  0.099022 -0.747121  1.066118  2.835370  1.165140
B  2.742849  2.984470 -0.170398  1.384525  2.572451
C  1.037328 -0.318614 -0.101749 -0.091330  0.935579
D  2.341230  0.528923 -0.507544  1.312976  1.833686
E  1.283571 -0.322914 -0.247309 -1.025842  1.036262

In [79]:
df.drop('New', axis=1)

W         X         Y         Z
A  0.099022 -0.747121  1.066118  2.835370
B  2.742849  2.984470 -0.170398  1.384525
C  1.037328 -0.318614 -0.101749 -0.091330
D  2.341230  0.528923 -0.507544  1.312976
E  1.283571 -0.322914 -0.247309 -1.025842

In [81]:
df.drop('New', axis=1, inplace=True)

In [82]:
df

W         X         Y         Z
A  0.099022 -0.747121  1.066118  2.835370
B  2.742849  2.984470 -0.170398  1.384525
C  1.037328 -0.318614 -0.101749 -0.091330
D  2.341230  0.528923 -0.507544  1.312976
E  1.283571 -0.322914 -0.247309 -1.025842