<a href='https://www2.howard.edu'> <img src='../hu_logo.png'/></a>

In [9]:
import numpy as np
import pandas as pd

In [10]:
array_1 = np.array([1,2,3,4])

In [11]:
array_2 = np.array([4,3,2,1])

In [12]:
len(array_1)+1

5

In [13]:
# for i in range(len(array_1)):
#     dot = sum(array_1[i]*array_2)
#     dot
#     #Do not use this

In [15]:
dot = 0
for e,f in zip(array_1,array_2):
    dot += e*f
dot

20

In [16]:
dot

20

In [17]:
array_1@array_2

20

In [18]:
array_1.dot(array_2)

20

In [19]:
array_3 = np.sqrt(array_1)

In [20]:
array_3

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [21]:
another_arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [22]:
another_arr[0:5]

array([1, 2, 3, 4, 5])

# Broadcasting

In [23]:
another_arr[0:5]=100

In [24]:
another_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [25]:
another_arr[:] = 1

In [26]:
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
three_by_three = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [28]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#three_by_three[:]  = 0

In [30]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# I want to grab the first column in three_by_three

In [32]:
three_by_three[0]

array([1, 2, 3])

In [33]:
#Slicing _ HW due this Monday.

In [34]:
three_by_three > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [35]:
new_matrix = three_by_three > 4

In [36]:
new_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [37]:
# Split method

In [38]:
# Given a string s ='a b c d', I want to find a list in the form ['a','b', 'c','d']

In [39]:
s ='a b c d'
a_list = []
for char in s:
    if char == ' ':
        continue
    else:
        a_list.append(char)
    a_list

In [40]:
a_list

['a', 'b', 'c', 'd']

In [41]:
s.split()

['a', 'b', 'c', 'd']

In [42]:
s = 'ab,c,d'

In [43]:
s.split(',')

['ab', 'c', 'd']

In [44]:
from numpy.random import randn

In [45]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [46]:
df

W         X         Y         Z
A -1.150203  0.612643  0.417190  1.600280
B  0.901492 -0.776925  0.869118  2.189686
C -0.533522  1.659293 -0.486862 -0.994356
D  0.242354 -0.273306  0.176446  0.456513
E  0.017466  1.165518  0.070643 -1.325575

In [47]:
df['W']

A   -1.150203
B    0.901492
C   -0.533522
D    0.242354
E    0.017466
Name: W, dtype: float64

In [48]:
# I want to grab the first two columns
df[['W', 'X']]

W         X
A -1.150203  0.612643
B  0.901492 -0.776925
C -0.533522  1.659293
D  0.242354 -0.273306
E  0.017466  1.165518

In [49]:
type(df.W)

pandas.core.series.Series

In [50]:
df['New'] = df['W']+df['Y']

In [51]:
df

W         X         Y         Z       New
A -1.150203  0.612643  0.417190  1.600280 -0.733013
B  0.901492 -0.776925  0.869118  2.189686  1.770609
C -0.533522  1.659293 -0.486862 -0.994356 -1.020385
D  0.242354 -0.273306  0.176446  0.456513  0.418800
E  0.017466  1.165518  0.070643 -1.325575  0.088108

In [52]:
df.drop('New', axis=1)

W         X         Y         Z
A -1.150203  0.612643  0.417190  1.600280
B  0.901492 -0.776925  0.869118  2.189686
C -0.533522  1.659293 -0.486862 -0.994356
D  0.242354 -0.273306  0.176446  0.456513
E  0.017466  1.165518  0.070643 -1.325575

In [53]:
df.drop('New', axis=1, inplace=True)

In [54]:
df

W         X         Y         Z
A -1.150203  0.612643  0.417190  1.600280
B  0.901492 -0.776925  0.869118  2.189686
C -0.533522  1.659293 -0.486862 -0.994356
D  0.242354 -0.273306  0.176446  0.456513
E  0.017466  1.165518  0.070643 -1.325575