<a href='https://www2.howard.edu'> <img src='../hu_logo.png'/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
array_1 = np.array([1,2,3,4])

In [5]:
array_2 = np.array([4,3,2,1])

In [21]:
len(array_1)+1

5

In [22]:
# for i in range(len(array_1)):
#     dot = sum(array_1[i]*array_2)
#     dot
#     #Do not use this

In [4]:
for e,f in zip(array_1,array_2):
    dot += e*f
    dot

NameError: name 'array_2' is not defined

In [24]:
dot

100

In [14]:
array_1@array_2

20

In [15]:
array_1.dot(array_2)

20

In [16]:
array_3 = np.sqrt(array_1)

In [10]:
array_3

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [11]:
another_arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [12]:
another_arr[0:5]

array([1, 2, 3, 4, 5])

# Broadcasting

In [13]:
another_arr[0:5]=100

In [14]:
another_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [15]:
another_arr[:] = 1

In [16]:
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
three_by_three = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [18]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#three_by_three[:]  = 0

In [20]:
three_by_three

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# I want to grab the first column in three_by_three

In [22]:
three_by_three[0]

array([1, 2, 3])

In [23]:
#Slicing _ HW due this Monday.

In [24]:
three_by_three > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [25]:
new_matrix = three_by_three > 4

In [26]:
new_matrix

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [27]:
# Split method

In [28]:
# Given a string s ='a b c d', I want to find a list in the form ['a','b', 'c','d']

In [29]:
s ='a b c d'
a_list = []
for char in s:
    if char == ' ':
        continue
    else:
        a_list.append(char)
    a_list

In [30]:
a_list

['a', 'b', 'c', 'd']

In [31]:
s.split()

['a', 'b', 'c', 'd']

In [32]:
s = 'ab,c,d'

In [33]:
s.split(',')

['ab', 'c', 'd']

In [34]:
from numpy.random import randn

In [35]:
df = pd.DataFrame(randn(5,4),index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [36]:
df

W         X         Y         Z
A -1.092147  0.425968  0.473625 -0.145116
B  1.262470  0.434551  1.215030  0.371328
C  1.238505  1.119650  0.688923 -0.252406
D -1.775382  2.505768  0.990656 -0.124809
E -1.782485 -0.214189  0.986656 -1.081272

In [37]:
df['W']

A   -1.092147
B    1.262470
C    1.238505
D   -1.775382
E   -1.782485
Name: W, dtype: float64

In [38]:
# I want to grab the first two columns
df[['W', 'X']]

W         X
A -1.092147  0.425968
B  1.262470  0.434551
C  1.238505  1.119650
D -1.775382  2.505768
E -1.782485 -0.214189

In [39]:
type(df.W)

pandas.core.series.Series

In [40]:
df['New'] = df['W']+df['Y']

In [41]:
df

W         X         Y         Z       New
A -1.092147  0.425968  0.473625 -0.145116 -0.618521
B  1.262470  0.434551  1.215030  0.371328  2.477499
C  1.238505  1.119650  0.688923 -0.252406  1.927428
D -1.775382  2.505768  0.990656 -0.124809 -0.784726
E -1.782485 -0.214189  0.986656 -1.081272 -0.795828

In [42]:
df.drop('New', axis=1)

W         X         Y         Z
A -1.092147  0.425968  0.473625 -0.145116
B  1.262470  0.434551  1.215030  0.371328
C  1.238505  1.119650  0.688923 -0.252406
D -1.775382  2.505768  0.990656 -0.124809
E -1.782485 -0.214189  0.986656 -1.081272

In [43]:
df.drop('New', axis=1, inplace=True)

In [44]:
df

W         X         Y         Z
A -1.092147  0.425968  0.473625 -0.145116
B  1.262470  0.434551  1.215030  0.371328
C  1.238505  1.119650  0.688923 -0.252406
D -1.775382  2.505768  0.990656 -0.124809
E -1.782485 -0.214189  0.986656 -1.081272